### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by JLiLab** [MontpellierRessourcesImagerie/napari-J#3]
Thank you for generating the plugin. When I tried to run, I got the following error message: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File ~/miniconda3/envs/napari-env/lib/python3.9/site-packages/napari_j/image.py:80, in Image._on_click_get_image(self=<napari_j.image.Image object>)
     79 def _on_click_get_image(self):
---> 80 	self.getImage()
        self = <napari_j.image.Image object at 0x1971c1e50>

File ~/miniconda3/envs/napari-env/lib/python3.9/site-packages/napari_j/image.py:105, in Image.getImage(self=<napari_j.image.Image object>)
    103 def getImage(self):
    104     print("Fetching the active image from IJ")
--> 105     self.getBridge().getActiveImageFromIJ()	 
        self = <napari_j.image.Image object at 0x1971c1e50>

File ~/miniconda3/envs/napari-env/lib/python3.9/site-packages/napari_j/image.py:98, in Image.getBridge(self=<napari_j.image.Image object>)
     97 def getBridge(self):
---> 98     from .bridge import Bridge
     99     if not self.bridge:
    100         self.bridge = Bridge(self.viewer)

File ~/miniconda3/envs/napari-env/lib/python3.9/site-packages/napari_j/bridge.py:9
      7 from jpype.types import *
      8 import numpy as np
----> 9 from ij.measure import ResultsTable
     10 from ij import IJ, ImagePlus, WindowManager
     11 from ij.plugin import HyperStackConverter

File ~/miniconda3/envs/napari-env/lib/python3.9/site-packages/ij/__init__.py:15
     12 from itertools import chain
     13 from operator import add
---> 15 from ut.ml.sk.feature_extraction.text import TreeTokenizer
     16 from functools import reduce
     18 path_separator_pattern = re.compile('/+')

ModuleNotFoundError: No module named 'ut'

**Comment by volker-baecker** [comment]
Hi @JLiLab 
what is your operating system? What is the napari version?
Did you install the plugin from within napari?

Seems like ``ut`` is missing, whatever that is?

I didn't encounter that problem so far, using either ubuntu or windows 11.

Best,
Volker

**Comment by JLiLab** [comment]
I ran into the same problem on Windows 10 and OSX. I installed the plugin within Napari. I just tried it on my Mac and Naparai crashed whenever I use the plugin. The message is as follows:

Starting jvm...
[WARNING] 2 exceptions occurred during plugin discovery.
Error while executing the main() method of class 'net.imagej.Main':
java.lang.IllegalArgumentException: Invalid service: sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:278)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:285)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:75)
	at net.imagej.Main.main(Main.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:87)
Caused by: java.lang.IllegalArgumentException: Invalid service: sc.fiji.bdvpg.scijava.services.SourceAndConverterService
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:278)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:339)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	... 16 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	... 19 more
Caused by: java.lang.RuntimeException: No _hooks field found in ij.IJ
It appears that this class was already defined in the class loader!
Please make sure that you initialize the LegacyService before using
any ImageJ 1.x class. You can do that by adding this static initializer:

	static {
		LegacyInjector.preinit();
	}

To debug this issue, start the JVM with the option:

	-javaagent:/Applications/Fiji.app/jars/ij1-patcher-1.2.2.jar

To enforce pre-initialization, start the JVM with the option:

	-javaagent:/Applications/Fiji.app/jars/ij1-patcher-1.2.2.jar=init

	at net.imagej.patcher.CodeHacker.javaAgentHint(CodeHacker.java:826)
	at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:433)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:380)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.<clinit>(SourceAndConverterService.java:132)
	... 28 more
Caused by: java.lang.NoSuchFieldException: _hooks
	at java.base/java.lang.Class.getField(Class.java:2117)
	at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:424)
	... 31 more
WARNING: QObject::~QObject: Timers cannot be stopped from another thread

**Comment by volker-baecker** [comment]
Hi @JLiLab,
the plugin will not work on Mac. Sorry, I should have made this clear in the readme. I'll update the readme. I'll also try to get my hands on a Mac to see if I can find a way around the problem (but it's not very likely).

So let's come back to the problem you encounter on windows. Can you try with a vanilla version of FIJI (no additional plugins installed) and see if it works. I sometimes had a problem when the same plugin was present multiple times. Also plugins using native code can be tricky.
Best,
Volker
